/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import components.PaginationItemRenderStyle1;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LE MINH
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        this.setLocationRelativeTo(null);
        setVisibleAllView();
        ViewBanHang.setVisible(true);
        pagination1.setPaginationItemRender(new PaginationItemRenderStyle1());
        pagination1.setPagegination(1, 10);
    }
    
    private void setVisibleAllView() {
        ViewBanHang.setVisible(false);
        ViewNhanVien.setVisible(false);
        ViewDoiMatKhau.setVisible(false);
        ViewHoaDon.setVisible(false);
        ViewKhuyenMai.setVisible(false);
        ViewThongKe.setVisible(false);
        ViewKhachHang.setVisible(false);
        ViewSanPham.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnShowViewBanHang = new javax.swing.JLabel();
        btnShowViewSanPham = new javax.swing.JLabel();
        btnShowViewNhanVien = new javax.swing.JLabel();
        btnShowViewKhachHang = new javax.swing.JLabel();
        btnShowViewThongKe = new javax.swing.JLabel();
        btnShowViewDoiMatKhau = new javax.swing.JLabel();
        btnShowViewHoaDon = new javax.swing.JLabel();
        btnShowViewBanHang1 = new javax.swing.JLabel();
        btnShowViewDoiMatKhau1 = new javax.swing.JLabel();
        btnShowViewBanHang2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnShowViewBanHang3 = new javax.swing.JLabel();
        btnShowViewBanHang4 = new javax.swing.JLabel();
        btnShowViewBanHang5 = new javax.swing.JLabel();
        btnShowViewBanHang6 = new javax.swing.JLabel();
        btnShowViewBanHang7 = new javax.swing.JLabel();
        btnShowViewBanHang8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ViewBanHang = new javax.swing.JPanel();
        tabbedPaneCustom1 = new components.TabbedPaneCustom();
        jPanel4 = new javax.swing.JPanel();
        buttonCustom1 = new components.ButtonCustom();
        buttonCustom3 = new components.ButtonCustom();
        buttonCustom4 = new components.ButtonCustom();
        buttonCustom5 = new components.ButtonCustom();
        jScrollPane4 = new javax.swing.JScrollPane();
        table2 = new components.Table();
        panelRound1 = new components.PanelRound();
        textField1 = new components.TextField();
        textField5 = new components.TextField();
        buttonCustom8 = new components.ButtonCustom();
        textField6 = new components.TextField();
        textField7 = new components.TextField();
        textField8 = new components.TextField();
        textField9 = new components.TextField();
        textField10 = new components.TextField();
        combobox5 = new components.Combobox();
        textField11 = new components.TextField();
        textField12 = new components.TextField();
        textField13 = new components.TextField();
        buttonCustom9 = new components.ButtonCustom();
        tabbedPaneCustom2 = new components.TabbedPaneCustom();
        jPanel6 = new javax.swing.JPanel();
        buttonCustom6 = new components.ButtonCustom();
        buttonCustom7 = new components.ButtonCustom();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new components.Table();
        tabbedPaneCustom3 = new components.TabbedPaneCustom();
        jPanel7 = new javax.swing.JPanel();
        pagination1 = new components.Pagination();
        combobox1 = new components.Combobox();
        combobox2 = new components.Combobox();
        combobox3 = new components.Combobox();
        combobox4 = new components.Combobox();
        textField4 = new components.TextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        table3 = new components.Table();
        ViewSanPham = new javax.swing.JPanel();
        materialTabbed1 = new components.MaterialTabbed();
        jPanel5 = new javax.swing.JPanel();
        textFieldSuggestion1 = new components.TextFieldSuggestion();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textFieldSuggestion2 = new components.TextFieldSuggestion();
        jLabel3 = new javax.swing.JLabel();
        textAreaScroll1 = new components.TextAreaScroll();
        textArea2 = new components.TextArea();
        jLabel4 = new javax.swing.JLabel();
        combobox6 = new components.Combobox();
        buttonCustom2 = new components.ButtonCustom();
        buttonCustom13 = new components.ButtonCustom();
        buttonCustom11 = new components.ButtonCustom();
        buttonCustom10 = new components.ButtonCustom();
        jLabel14 = new javax.swing.JLabel();
        combobox13 = new components.Combobox();
        jLabel15 = new javax.swing.JLabel();
        combobox14 = new components.Combobox();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        textFieldSuggestion3 = new components.TextFieldSuggestion();
        jLabel7 = new javax.swing.JLabel();
        textFieldSuggestion4 = new components.TextFieldSuggestion();
        textFieldSuggestion5 = new components.TextFieldSuggestion();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        combobox8 = new components.Combobox();
        jLabel10 = new javax.swing.JLabel();
        combobox9 = new components.Combobox();
        jLabel11 = new javax.swing.JLabel();
        combobox10 = new components.Combobox();
        jLabel12 = new javax.swing.JLabel();
        combobox11 = new components.Combobox();
        btnShowViewSole = new components.ButtonCustom();
        btnShowViewSize = new components.ButtonCustom();
        btnShowViewColor = new components.ButtonCustom();
        btnShowViewMaterial = new components.ButtonCustom();
        jLabel13 = new javax.swing.JLabel();
        buttonCustom12 = new components.ButtonCustom();
        buttonCustom14 = new components.ButtonCustom();
        buttonCustom15 = new components.ButtonCustom();
        jLabel16 = new javax.swing.JLabel();
        textFieldSuggestion6 = new components.TextFieldSuggestion();
        jScrollPane7 = new javax.swing.JScrollPane();
        table6 = new components.Table();
        jLabel8 = new javax.swing.JLabel();
        textField15 = new components.TextField();
        combobox12 = new components.Combobox();
        pagination3 = new components.Pagination();
        ViewNhanVien = new javax.swing.JPanel();
        ViewThongKe = new javax.swing.JPanel();
        ViewKhachHang = new javax.swing.JPanel();
        ViewDoiMatKhau = new javax.swing.JPanel();
        ViewKhuyenMai = new javax.swing.JPanel();
        ViewHoaDon = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(30, 144, 255));

        btnShowViewBanHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnShowViewBanHang.setForeground(new java.awt.Color(255, 255, 255));
        btnShowViewBanHang.setText("Bán hàng");
        btnShowViewBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowViewBanHangMouseClicked(evt);
            }
        });

        btnShowViewSanPham.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnShowViewSanPham.setForeground(new java.awt.Color(255, 255, 255));
        btnShowViewSanPham.setText("Sản phẩm");
        btnShowViewSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowViewSanPhamMouseClicked(evt);
            }
        });

        btnShowViewNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnShowViewNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btnShowViewNhanVien.setText("Nhân viên");
        btnShowViewNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowViewNhanVienMouseClicked(evt);
            }
        });

        btnShowViewKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnShowViewKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        btnShowViewKhachHang.setText("Khách hàng");
        btnShowViewKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowViewKhachHangMouseClicked(evt);
            }
        });

        btnShowViewThongKe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnShowViewThongKe.setForeground(new java.awt.Color(255, 255, 255));
        btnShowViewThongKe.setText("Thống kê");
        btnShowViewThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowViewThongKeMouseClicked(evt);
            }
        });

        btnShowViewDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnShowViewDoiMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        btnShowViewDoiMatKhau.setText("Đổi mật khẩu");
        btnShowViewDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowViewDoiMatKhauMouseClicked(evt);
            }
        });

        btnShowViewHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnShowViewHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btnShowViewHoaDon.setText("Hoá đơn");
        btnShowViewHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowViewHoaDonMouseClicked(evt);
            }
        });

        btnShowViewBanHang1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnShowViewBanHang1.setForeground(new java.awt.Color(255, 255, 255));
        btnShowViewBanHang1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-staff-30.png"))); // NOI18N
        btnShowViewBanHang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowViewBanHang1MouseClicked(evt);
            }
        });

        btnShowViewDoiMatKhau1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnShowViewDoiMatKhau1.setForeground(new java.awt.Color(255, 255, 255));
        btnShowViewDoiMatKhau1.setText("Đăng xuất");
        btnShowViewDoiMatKhau1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowViewDoiMatKhau1MouseClicked(evt);
            }
        });

        btnShowViewBanHang2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnShowViewBanHang2.setForeground(new java.awt.Color(255, 255, 255));
        btnShowViewBanHang2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-bonds-30.png"))); // NOI18N
        btnShowViewBanHang2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowViewBanHang2MouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.jpg"))); // NOI18N

        btnShowViewBanHang3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnShowViewBanHang3.setForeground(new java.awt.Color(255, 255, 255));
        btnShowViewBanHang3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-staff-30.png"))); // NOI18N
        btnShowViewBanHang3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowViewBanHang3MouseClicked(evt);
            }
        });

        btnShowViewBanHang4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnShowViewBanHang4.setForeground(new java.awt.Color(255, 255, 255));
        btnShowViewBanHang4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-staff-30.png"))); // NOI18N
        btnShowViewBanHang4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowViewBanHang4MouseClicked(evt);
            }
        });

        btnShowViewBanHang5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnShowViewBanHang5.setForeground(new java.awt.Color(255, 255, 255));
        btnShowViewBanHang5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-staff-30.png"))); // NOI18N
        btnShowViewBanHang5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowViewBanHang5MouseClicked(evt);
            }
        });

        btnShowViewBanHang6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnShowViewBanHang6.setForeground(new java.awt.Color(255, 255, 255));
        btnShowViewBanHang6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-staff-30.png"))); // NOI18N
        btnShowViewBanHang6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowViewBanHang6MouseClicked(evt);
            }
        });

        btnShowViewBanHang7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnShowViewBanHang7.setForeground(new java.awt.Color(255, 255, 255));
        btnShowViewBanHang7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-load-38.png"))); // NOI18N
        btnShowViewBanHang7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowViewBanHang7MouseClicked(evt);
            }
        });

        btnShowViewBanHang8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnShowViewBanHang8.setForeground(new java.awt.Color(255, 255, 255));
        btnShowViewBanHang8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-staff-30.png"))); // NOI18N
        btnShowViewBanHang8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowViewBanHang8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnShowViewBanHang1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnShowViewBanHang2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnShowViewBanHang3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnShowViewBanHang4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnShowViewBanHang5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnShowViewBanHang6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnShowViewBanHang7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnShowViewBanHang8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnShowViewNhanVien)
                    .addComponent(btnShowViewThongKe)
                    .addComponent(btnShowViewHoaDon)
                    .addComponent(btnShowViewDoiMatKhau)
                    .addComponent(btnShowViewDoiMatKhau1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnShowViewBanHang)
                        .addComponent(btnShowViewSanPham))
                    .addComponent(btnShowViewKhachHang))
                .addGap(53, 53, 53))
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnShowViewBanHang)
                                            .addComponent(btnShowViewBanHang2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(44, 44, 44)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnShowViewSanPham)
                                            .addComponent(btnShowViewBanHang3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(50, 50, 50)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnShowViewKhachHang)
                                            .addComponent(btnShowViewBanHang1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(55, 55, 55)
                                        .addComponent(btnShowViewNhanVien))
                                    .addComponent(btnShowViewBanHang4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnShowViewThongKe)
                                    .addComponent(btnShowViewBanHang5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addComponent(btnShowViewHoaDon))
                            .addComponent(btnShowViewBanHang6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addComponent(btnShowViewDoiMatKhau))
                    .addComponent(btnShowViewBanHang7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnShowViewDoiMatKhau1)
                    .addComponent(btnShowViewBanHang8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 800));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new javax.swing.OverlayLayout(jPanel2));

        ViewBanHang.setBackground(new java.awt.Color(255, 255, 255));

        tabbedPaneCustom1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabbedPaneCustom1.setForeground(new java.awt.Color(255, 255, 255));
        tabbedPaneCustom1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        buttonCustom1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-plus-38 (1).png"))); // NOI18N
        buttonCustom1.setColor1(new java.awt.Color(102, 102, 102));
        buttonCustom1.setColor2(new java.awt.Color(102, 102, 102));

        buttonCustom3.setText("Huỷ hoá đơn");
        buttonCustom3.setColor1(new java.awt.Color(255, 51, 102));
        buttonCustom3.setColor2(new java.awt.Color(255, 0, 51));
        buttonCustom3.setFont(new java.awt.Font("Source Sans Pro SemiBold", 1, 14)); // NOI18N

        buttonCustom4.setText("Làm mới");
        buttonCustom4.setColor1(new java.awt.Color(0, 153, 255));
        buttonCustom4.setColor2(new java.awt.Color(0, 102, 255));
        buttonCustom4.setFont(new java.awt.Font("Source Sans Pro SemiBold", 1, 14)); // NOI18N

        buttonCustom5.setText("Chọn voucher");
        buttonCustom5.setColor1(new java.awt.Color(0, 153, 255));
        buttonCustom5.setColor2(new java.awt.Color(0, 102, 255));
        buttonCustom5.setFont(new java.awt.Font("Source Sans Pro SemiBold", 1, 14)); // NOI18N

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table2.setRowHeight(30);
        jScrollPane4.setViewportView(table2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(buttonCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonCustom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 486, Short.MAX_VALUE)
                .addComponent(buttonCustom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCustom5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonCustom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonCustom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonCustom5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(59, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(1, 1, 1)))
        );

        tabbedPaneCustom1.addTab("Hoá đơn đang chờ", jPanel4);

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Đơn hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        textField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textField1.setLabelText("Mã hoá đơn:");

        textField5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textField5.setLabelText("Mã khách hàng:");

        buttonCustom8.setText("Chọn");
        buttonCustom8.setColor1(new java.awt.Color(255, 51, 102));
        buttonCustom8.setColor2(new java.awt.Color(255, 0, 51));
        buttonCustom8.setFont(new java.awt.Font("Source Sans Pro SemiBold", 1, 14)); // NOI18N

        textField6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textField6.setLabelText("Số điện thoại:");

        textField7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textField7.setLabelText("Họ và tên:");

        textField8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textField8.setLabelText("Tạm tính:");

        textField9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textField9.setLabelText("Số tiền được giảm:");

        textField10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textField10.setLabelText("Tổng tiền:");

        combobox5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        combobox5.setLabeText("Hình thức thanh toán");
        combobox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox5ActionPerformed(evt);
            }
        });

        textField11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textField11.setLabelText("Tiền mặt:");

        textField12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textField12.setLabelText("Chuyển khoản:");

        textField13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textField13.setLabelText("Tiền trả lại:");

        buttonCustom9.setText("Thanh toán");
        buttonCustom9.setColor1(new java.awt.Color(0, 255, 51));
        buttonCustom9.setColor2(new java.awt.Color(51, 255, 51));
        buttonCustom9.setFont(new java.awt.Font("Source Sans Pro SemiBold", 1, 14)); // NOI18N

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addComponent(textField5, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonCustom8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textField6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textField7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textField8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textField9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textField10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combobox5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(textField11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textField12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textField13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(buttonCustom9, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCustom8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(combobox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(buttonCustom9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        tabbedPaneCustom2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabbedPaneCustom2.setForeground(new java.awt.Color(255, 255, 255));
        tabbedPaneCustom2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        buttonCustom6.setText("Xoá");
        buttonCustom6.setColor1(new java.awt.Color(255, 51, 102));
        buttonCustom6.setColor2(new java.awt.Color(255, 0, 51));
        buttonCustom6.setFont(new java.awt.Font("Source Sans Pro SemiBold", 1, 14)); // NOI18N

        buttonCustom7.setText("Sửa số lượng");
        buttonCustom7.setColor1(new java.awt.Color(0, 153, 255));
        buttonCustom7.setColor2(new java.awt.Color(0, 102, 255));
        buttonCustom7.setFont(new java.awt.Font("Source Sans Pro SemiBold", 1, 14)); // NOI18N

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table1.setRowHeight(30);
        jScrollPane2.setViewportView(table1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 668, Short.MAX_VALUE)
                        .addComponent(buttonCustom7, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonCustom6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCustom6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCustom7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
        );

        tabbedPaneCustom2.addTab("Giỏ hàng", jPanel6);

        tabbedPaneCustom3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabbedPaneCustom3.setForeground(new java.awt.Color(255, 255, 255));
        tabbedPaneCustom3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        pagination1.setBackground(new java.awt.Color(204, 204, 204));
        pagination1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        combobox1.setLabeText("Màu sắc");
        combobox1.setLineColor(new java.awt.Color(255, 0, 0));

        combobox2.setLabeText("Kích cỡ");
        combobox2.setLineColor(new java.awt.Color(255, 0, 0));

        combobox3.setLabeText("Chất liệu");
        combobox3.setLineColor(new java.awt.Color(255, 0, 0));
        combobox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox3ActionPerformed(evt);
            }
        });

        combobox4.setLabeText("Hãng");
        combobox4.setLineColor(new java.awt.Color(255, 0, 0));

        textField4.setLabelText("Tên sản phẩm");

        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table3.setRowHeight(30);
        jScrollPane5.setViewportView(table3);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(combobox4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combobox2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combobox3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combobox1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                        .addComponent(textField4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(pagination1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane5)
                    .addContainerGap()))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(190, 190, 190)
                .addComponent(pagination1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(52, Short.MAX_VALUE)))
        );

        tabbedPaneCustom3.addTab("Sản phẩm", jPanel7);

        javax.swing.GroupLayout ViewBanHangLayout = new javax.swing.GroupLayout(ViewBanHang);
        ViewBanHang.setLayout(ViewBanHangLayout);
        ViewBanHangLayout.setHorizontalGroup(
            ViewBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewBanHangLayout.createSequentialGroup()
                .addGroup(ViewBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewBanHangLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(ViewBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tabbedPaneCustom2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tabbedPaneCustom3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewBanHangLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tabbedPaneCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        ViewBanHangLayout.setVerticalGroup(
            ViewBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewBanHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ViewBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ViewBanHangLayout.createSequentialGroup()
                        .addComponent(tabbedPaneCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tabbedPaneCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabbedPaneCustom3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2.add(ViewBanHang);

        ViewSanPham.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Mã sản phẩm:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Tên sản phẩm:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Mô tả:");

        textAreaScroll1.setLabelText("Description...");

        textArea2.setColumns(20);
        textArea2.setRows(5);
        textAreaScroll1.setViewportView(textArea2);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Hãng:");

        combobox6.setLabeText("");

        buttonCustom2.setText("Thêm");
        buttonCustom2.setColor1(new java.awt.Color(0, 255, 51));
        buttonCustom2.setColor2(new java.awt.Color(51, 255, 51));
        buttonCustom2.setFont(new java.awt.Font("Source Sans Pro SemiBold", 1, 14)); // NOI18N

        buttonCustom13.setText("Sửa");
        buttonCustom13.setColor1(new java.awt.Color(255, 204, 0));
        buttonCustom13.setColor2(new java.awt.Color(255, 255, 0));
        buttonCustom13.setFont(new java.awt.Font("Source Sans Pro SemiBold", 1, 14)); // NOI18N

        buttonCustom11.setText("Xoá");
        buttonCustom11.setColor1(new java.awt.Color(255, 51, 102));
        buttonCustom11.setColor2(new java.awt.Color(255, 0, 51));
        buttonCustom11.setFont(new java.awt.Font("Source Sans Pro SemiBold", 1, 14)); // NOI18N

        buttonCustom10.setText("Làm mới");
        buttonCustom10.setColor1(new java.awt.Color(0, 153, 255));
        buttonCustom10.setColor2(new java.awt.Color(0, 102, 255));
        buttonCustom10.setFont(new java.awt.Font("Source Sans Pro SemiBold", 1, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Thể loại:");

        combobox13.setLabeText("Xuất xứ");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Xuất xứ:");

        combobox14.setLabeText("Thể loại");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(textFieldSuggestion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(textFieldSuggestion2, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(combobox6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textAreaScroll1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                                .addComponent(combobox13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel15))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(75, 75, 75)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(buttonCustom11, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(72, 72, 72)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(buttonCustom10, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonCustom13, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel14)
                                    .addGap(287, 287, 287)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(combobox14, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)))))
                .addGap(38, 38, 38))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel15))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldSuggestion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combobox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(textFieldSuggestion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combobox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textAreaScroll1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combobox14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCustom13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonCustom11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCustom10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        materialTabbed1.addTab("Sản phẩm", jPanel5);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Tên sản phẩm:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Giá nhập:");

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Thuộc tính"));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Màu sắc:");

        combobox8.setLabeText("Màu sắc");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Kích cỡ:");

        combobox9.setLabeText("Size");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Chất liệu:");

        combobox10.setLabeText("Đế giày");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Đế giày:");

        combobox11.setLabeText("Chất liệu");

        btnShowViewSole.setText("Xem");
        btnShowViewSole.setColor1(new java.awt.Color(0, 0, 255));
        btnShowViewSole.setColor2(new java.awt.Color(0, 102, 255));
        btnShowViewSole.setFont(new java.awt.Font("Source Sans Pro SemiBold", 1, 14)); // NOI18N
        btnShowViewSole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowViewSoleActionPerformed(evt);
            }
        });

        btnShowViewSize.setText("Xem");
        btnShowViewSize.setColor1(new java.awt.Color(0, 0, 255));
        btnShowViewSize.setColor2(new java.awt.Color(0, 102, 255));
        btnShowViewSize.setFont(new java.awt.Font("Source Sans Pro SemiBold", 1, 14)); // NOI18N
        btnShowViewSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowViewSizeActionPerformed(evt);
            }
        });

        btnShowViewColor.setText("Xem");
        btnShowViewColor.setColor1(new java.awt.Color(0, 0, 255));
        btnShowViewColor.setColor2(new java.awt.Color(0, 102, 255));
        btnShowViewColor.setFont(new java.awt.Font("Source Sans Pro SemiBold", 1, 14)); // NOI18N
        btnShowViewColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowViewColorActionPerformed(evt);
            }
        });

        btnShowViewMaterial.setText("Xem");
        btnShowViewMaterial.setColor1(new java.awt.Color(0, 0, 255));
        btnShowViewMaterial.setColor2(new java.awt.Color(0, 102, 255));
        btnShowViewMaterial.setFont(new java.awt.Font("Source Sans Pro SemiBold", 1, 14)); // NOI18N
        btnShowViewMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowViewMaterialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(combobox10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combobox8, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                            .addComponent(combobox9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combobox11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnShowViewSole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShowViewSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShowViewColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShowViewMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(btnShowViewColor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(btnShowViewSize, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(btnShowViewSole, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(btnShowViewMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Giá bán:");

        buttonCustom12.setText("Lưu");
        buttonCustom12.setColor1(new java.awt.Color(0, 255, 51));
        buttonCustom12.setColor2(new java.awt.Color(51, 255, 51));
        buttonCustom12.setFont(new java.awt.Font("Source Sans Pro SemiBold", 1, 14)); // NOI18N

        buttonCustom14.setText("Thêm");
        buttonCustom14.setColor1(new java.awt.Color(0, 255, 51));
        buttonCustom14.setColor2(new java.awt.Color(51, 255, 51));
        buttonCustom14.setFont(new java.awt.Font("Source Sans Pro SemiBold", 1, 14)); // NOI18N

        buttonCustom15.setText("Làm mới");
        buttonCustom15.setColor1(new java.awt.Color(0, 153, 255));
        buttonCustom15.setColor2(new java.awt.Color(0, 102, 255));
        buttonCustom15.setFont(new java.awt.Font("Source Sans Pro SemiBold", 1, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Số lượng:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(textFieldSuggestion3, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                    .addComponent(textFieldSuggestion4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFieldSuggestion5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(textFieldSuggestion6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCustom14, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCustom15, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(buttonCustom12, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldSuggestion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldSuggestion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(buttonCustom14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonCustom15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldSuggestion5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldSuggestion6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(buttonCustom12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        materialTabbed1.addTab("Chi tiết sản phẩm", jPanel8);

        table6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table6.setRowHeight(30);
        jScrollPane7.setViewportView(table6);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("#Danh sách sản phẩm");

        textField15.setLabelText("Tìm tên sản phẩm...");

        combobox12.setLabeText("Hãng");
        combobox12.setLineColor(new java.awt.Color(255, 0, 0));

        pagination3.setBackground(new java.awt.Color(204, 204, 204));
        pagination3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout ViewSanPhamLayout = new javax.swing.GroupLayout(ViewSanPham);
        ViewSanPham.setLayout(ViewSanPhamLayout);
        ViewSanPhamLayout.setHorizontalGroup(
            ViewSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewSanPhamLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(ViewSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pagination3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ViewSanPhamLayout.createSequentialGroup()
                        .addComponent(textField15, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combobox12, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 1188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(materialTabbed1, javax.swing.GroupLayout.PREFERRED_SIZE, 1170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        ViewSanPhamLayout.setVerticalGroup(
            ViewSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewSanPhamLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(materialTabbed1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ViewSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pagination3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jPanel2.add(ViewSanPham);

        ViewNhanVien.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout ViewNhanVienLayout = new javax.swing.GroupLayout(ViewNhanVien);
        ViewNhanVien.setLayout(ViewNhanVienLayout);
        ViewNhanVienLayout.setHorizontalGroup(
            ViewNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1230, Short.MAX_VALUE)
        );
        ViewNhanVienLayout.setVerticalGroup(
            ViewNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jPanel2.add(ViewNhanVien);

        ViewThongKe.setBackground(new java.awt.Color(204, 255, 51));

        javax.swing.GroupLayout ViewThongKeLayout = new javax.swing.GroupLayout(ViewThongKe);
        ViewThongKe.setLayout(ViewThongKeLayout);
        ViewThongKeLayout.setHorizontalGroup(
            ViewThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1230, Short.MAX_VALUE)
        );
        ViewThongKeLayout.setVerticalGroup(
            ViewThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jPanel2.add(ViewThongKe);

        ViewKhachHang.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout ViewKhachHangLayout = new javax.swing.GroupLayout(ViewKhachHang);
        ViewKhachHang.setLayout(ViewKhachHangLayout);
        ViewKhachHangLayout.setHorizontalGroup(
            ViewKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1230, Short.MAX_VALUE)
        );
        ViewKhachHangLayout.setVerticalGroup(
            ViewKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jPanel2.add(ViewKhachHang);

        ViewDoiMatKhau.setBackground(new java.awt.Color(102, 255, 0));

        javax.swing.GroupLayout ViewDoiMatKhauLayout = new javax.swing.GroupLayout(ViewDoiMatKhau);
        ViewDoiMatKhau.setLayout(ViewDoiMatKhauLayout);
        ViewDoiMatKhauLayout.setHorizontalGroup(
            ViewDoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1230, Short.MAX_VALUE)
        );
        ViewDoiMatKhauLayout.setVerticalGroup(
            ViewDoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jPanel2.add(ViewDoiMatKhau);

        ViewKhuyenMai.setBackground(new java.awt.Color(255, 102, 255));

        javax.swing.GroupLayout ViewKhuyenMaiLayout = new javax.swing.GroupLayout(ViewKhuyenMai);
        ViewKhuyenMai.setLayout(ViewKhuyenMaiLayout);
        ViewKhuyenMaiLayout.setHorizontalGroup(
            ViewKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1230, Short.MAX_VALUE)
        );
        ViewKhuyenMaiLayout.setVerticalGroup(
            ViewKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jPanel2.add(ViewKhuyenMai);

        ViewHoaDon.setBackground(new java.awt.Color(204, 102, 0));

        javax.swing.GroupLayout ViewHoaDonLayout = new javax.swing.GroupLayout(ViewHoaDon);
        ViewHoaDon.setLayout(ViewHoaDonLayout);
        ViewHoaDonLayout.setHorizontalGroup(
            ViewHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1230, Short.MAX_VALUE)
        );
        ViewHoaDonLayout.setVerticalGroup(
            ViewHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jPanel2.add(ViewHoaDon);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 1230, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowViewBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowViewBanHangMouseClicked
        // TODO add your handling code here:
        setVisibleAllView();
        ViewBanHang.setVisible(true);
    }//GEN-LAST:event_btnShowViewBanHangMouseClicked

    private void btnShowViewSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowViewSanPhamMouseClicked
        // TODO add your handling code here:
        setVisibleAllView();
        ViewSanPham.setVisible(true);
    }//GEN-LAST:event_btnShowViewSanPhamMouseClicked

    private void btnShowViewKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowViewKhachHangMouseClicked
        // TODO add your handling code here:
        setVisibleAllView();
        ViewKhachHang.setVisible(true);
    }//GEN-LAST:event_btnShowViewKhachHangMouseClicked

    private void btnShowViewNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowViewNhanVienMouseClicked
        // TODO add your handling code here:
        setVisibleAllView();
        ViewNhanVien.setVisible(true);
    }//GEN-LAST:event_btnShowViewNhanVienMouseClicked

    private void btnShowViewThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowViewThongKeMouseClicked
        // TODO add your handling code here:
        setVisibleAllView();
        ViewThongKe.setVisible(true);
    }//GEN-LAST:event_btnShowViewThongKeMouseClicked

    private void btnShowViewHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowViewHoaDonMouseClicked
        // TODO add your handling code here:
        setVisibleAllView();
        ViewHoaDon.setVisible(true);
    }//GEN-LAST:event_btnShowViewHoaDonMouseClicked

    private void btnShowViewDoiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowViewDoiMatKhauMouseClicked
        // TODO add your handling code here:
        setVisibleAllView();
        ViewDoiMatKhau.setVisible(true);
    }//GEN-LAST:event_btnShowViewDoiMatKhauMouseClicked

    private void btnShowViewBanHang1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowViewBanHang1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowViewBanHang1MouseClicked

    private void btnShowViewDoiMatKhau1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowViewDoiMatKhau1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowViewDoiMatKhau1MouseClicked

    private void combobox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox3ActionPerformed

    private void combobox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox5ActionPerformed

    private void btnShowViewColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowViewColorActionPerformed
        // TODO add your handling code here:
        new ViewChangeColorProduct(this, true).setVisible(true);
    }//GEN-LAST:event_btnShowViewColorActionPerformed

    private void btnShowViewSoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowViewSoleActionPerformed
        // TODO add your handling code here:
        new ViewChangSoleProduct(this, true).setVisible(true);
    }//GEN-LAST:event_btnShowViewSoleActionPerformed

    private void btnShowViewMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowViewMaterialActionPerformed
        // TODO add your handling code here:
        new ViewChangeMaterialProduct(this, true).setVisible(true);
    }//GEN-LAST:event_btnShowViewMaterialActionPerformed

    private void btnShowViewSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowViewSizeActionPerformed
        // TODO add your handling code here:
        new ViewChangeSizeProduct(this, true).setVisible(true);
    }//GEN-LAST:event_btnShowViewSizeActionPerformed

    private void btnShowViewBanHang2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowViewBanHang2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowViewBanHang2MouseClicked

    private void btnShowViewBanHang3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowViewBanHang3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowViewBanHang3MouseClicked

    private void btnShowViewBanHang4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowViewBanHang4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowViewBanHang4MouseClicked

    private void btnShowViewBanHang5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowViewBanHang5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowViewBanHang5MouseClicked

    private void btnShowViewBanHang6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowViewBanHang6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowViewBanHang6MouseClicked

    private void btnShowViewBanHang7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowViewBanHang7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowViewBanHang7MouseClicked

    private void btnShowViewBanHang8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowViewBanHang8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowViewBanHang8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ViewBanHang;
    private javax.swing.JPanel ViewDoiMatKhau;
    private javax.swing.JPanel ViewHoaDon;
    private javax.swing.JPanel ViewKhachHang;
    private javax.swing.JPanel ViewKhuyenMai;
    private javax.swing.JPanel ViewNhanVien;
    private javax.swing.JPanel ViewSanPham;
    private javax.swing.JPanel ViewThongKe;
    private javax.swing.JLabel btnShowViewBanHang;
    private javax.swing.JLabel btnShowViewBanHang1;
    private javax.swing.JLabel btnShowViewBanHang2;
    private javax.swing.JLabel btnShowViewBanHang3;
    private javax.swing.JLabel btnShowViewBanHang4;
    private javax.swing.JLabel btnShowViewBanHang5;
    private javax.swing.JLabel btnShowViewBanHang6;
    private javax.swing.JLabel btnShowViewBanHang7;
    private javax.swing.JLabel btnShowViewBanHang8;
    private components.ButtonCustom btnShowViewColor;
    private javax.swing.JLabel btnShowViewDoiMatKhau;
    private javax.swing.JLabel btnShowViewDoiMatKhau1;
    private javax.swing.JLabel btnShowViewHoaDon;
    private javax.swing.JLabel btnShowViewKhachHang;
    private components.ButtonCustom btnShowViewMaterial;
    private javax.swing.JLabel btnShowViewNhanVien;
    private javax.swing.JLabel btnShowViewSanPham;
    private components.ButtonCustom btnShowViewSize;
    private components.ButtonCustom btnShowViewSole;
    private javax.swing.JLabel btnShowViewThongKe;
    private components.ButtonCustom buttonCustom1;
    private components.ButtonCustom buttonCustom10;
    private components.ButtonCustom buttonCustom11;
    private components.ButtonCustom buttonCustom12;
    private components.ButtonCustom buttonCustom13;
    private components.ButtonCustom buttonCustom14;
    private components.ButtonCustom buttonCustom15;
    private components.ButtonCustom buttonCustom2;
    private components.ButtonCustom buttonCustom3;
    private components.ButtonCustom buttonCustom4;
    private components.ButtonCustom buttonCustom5;
    private components.ButtonCustom buttonCustom6;
    private components.ButtonCustom buttonCustom7;
    private components.ButtonCustom buttonCustom8;
    private components.ButtonCustom buttonCustom9;
    private components.Combobox combobox1;
    private components.Combobox combobox10;
    private components.Combobox combobox11;
    private components.Combobox combobox12;
    private components.Combobox combobox13;
    private components.Combobox combobox14;
    private components.Combobox combobox2;
    private components.Combobox combobox3;
    private components.Combobox combobox4;
    private components.Combobox combobox5;
    private components.Combobox combobox6;
    private components.Combobox combobox8;
    private components.Combobox combobox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private components.MaterialTabbed materialTabbed1;
    private components.Pagination pagination1;
    private components.Pagination pagination3;
    private components.PanelRound panelRound1;
    private components.TabbedPaneCustom tabbedPaneCustom1;
    private components.TabbedPaneCustom tabbedPaneCustom2;
    private components.TabbedPaneCustom tabbedPaneCustom3;
    private components.Table table1;
    private components.Table table2;
    private components.Table table3;
    private components.Table table6;
    private components.TextArea textArea2;
    private components.TextAreaScroll textAreaScroll1;
    private components.TextField textField1;
    private components.TextField textField10;
    private components.TextField textField11;
    private components.TextField textField12;
    private components.TextField textField13;
    private components.TextField textField15;
    private components.TextField textField4;
    private components.TextField textField5;
    private components.TextField textField6;
    private components.TextField textField7;
    private components.TextField textField8;
    private components.TextField textField9;
    private components.TextFieldSuggestion textFieldSuggestion1;
    private components.TextFieldSuggestion textFieldSuggestion2;
    private components.TextFieldSuggestion textFieldSuggestion3;
    private components.TextFieldSuggestion textFieldSuggestion4;
    private components.TextFieldSuggestion textFieldSuggestion5;
    private components.TextFieldSuggestion textFieldSuggestion6;
    // End of variables declaration//GEN-END:variables
}
